---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
 - src: git@github.com:suntsovvv/vector-role.git
    scm: git
    version: "v1.0.0"
    name: vector-role 
 - src: git@github.com:suntsovvv/lighthouse-role.git
    scm: git
    version: "v1.0.0"
    name: lighthouse-role