---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.97.40
      #ansible_user: ansible
      #ansible_connection: ssh
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.62.236
      #ansible_user: vector
      #ansible_connection: ssh
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.117.239
      ansible_user: lighthouse
      #ansible_connection: ssh